### ISSUE TITLE
How do I get output from the serial connection?

### ISSUE THREAD

**Issue by sirmxanot** [jcantara/em-rubyserial#1]
My use case is that I'm configuring a switch over a serial console connection. I'm able to send commands to the switch just fine. However, I want to validate output from the switch as in confirmation of my commands. I thought that this is what you're example was doing, but its not writing anything back even though i can see through a separate terminal that the commands are going through. Thanks!

**Comment by jcantara** [comment]
So, within the "serial.on_data" block in the example, does that block never get called, or data is empty? What OS/Ruby/etc are you using?

**Comment by jcantara** [comment]
Closing because no feedback.
